import { useContext } from 'react'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import AuthContext from '../util/contexts/AuthContext'

const Layout = ({ children }) => {
  const { state: { status, name } } = useContext( AuthContext )

  const logged = status === 'authenticated'

  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Kadince Todo App</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            { logged && `${name}'s` } Todos
          </h1>
          {children}
        </main>
      </div>
    </>
  )
}

export default Layout
