import { ToastContainer } from 'react-toastify'
import Head from 'next/head'
import CustomTable from '../components/Table'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Kadince Todo App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Todos
        </h1>
        <CustomTable />
        <ToastContainer
          position='bottom-right'
          autoClose={2000}
          hideProgressBar
          closeOnClick
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme='colored'
        />
      </main>
    </div>
  )
}
